Week6CodeChallenge/Models/CompanyContactPage.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week6CodeChallenge.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sp5JoshEntities1 : DbContext
    {
        public sp5JoshEntities1()
            : base("name=sp5JoshEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContactForm> ContactForms { get; set; }
    }
}

Week6CodeChallenge/Models/CompanyContactPage.Designer.cs
// T4 code generation is enabled for model 'C:\Users\Technologist SP\Documents\GitHub\Week6CodeChallenge\Week6CodeChallenge\Models\CompanyContactPage.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

Week6CodeChallenge/Models/CompanyContactPage.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

Week6CodeChallenge/Models/ContactForm.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week6CodeChallenge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactForm
    {
        public int contactID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string CompanyName { get; set; }
        public string ProjectDescription { get; set; }
        public string Comment { get; set; }
    }
}

Week6CodeChallenge/Models/ContactFormValidation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Week6CodeChallenge.Models
{
    public class ContactFormValidation
    {
    }
}

Week6CodeChallenge/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Week6CodeChallenge.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult Index()
        {
            if (Request.IsAjaxRequest())
            {
                return PartialView();
            }
            return View();
        }

        public ActionResult Who()
        {
            if (Request.IsAjaxRequest())
            {
                return PartialView();
            }
            return View();
        }

        public ActionResult What()
        {
            if (Request.IsAjaxRequest())
            {
                return PartialView();
            }
            return View();
        }

        public ActionResult Why()
        {
            if (Request.IsAjaxRequest())
            {
                return PartialView();
            }
            return View();
        }

        public ActionResult How()
        {
            if (Request.IsAjaxRequest())
            {
                return PartialView();
            }
            return View();
        }

        public ActionResult Where()
        {
            if (Request.IsAjaxRequest())
            {
                return PartialView();
            }
            return View();
        }
    }
}

Week6CodeChallenge/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Week6CodeChallenge.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        [HttpGet]
        public ActionResult Index()
        {
            if (Request.IsAjaxRequest())
            {
                return PartialView();
            }
            return View();
        }

        [HttpPost]
        public ActionResult Index(Models.ContactForm inputData)
        {
            Models.sp5JoshEntities1 db = new Models.sp5JoshEntities1();
            db.ContactForms.Add(inputData);
            db.SaveChanges();
            return Content("Thanks");
        }
    }
}

Week6CodeChallenge/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Week6CodeChallenge.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            if (Request.IsAjaxRequest())
            {
                return PartialView();
            }
            return View();
        }

        public ActionResult Work()
        {
            if (Request.IsAjaxRequest())
            {
                return PartialView();
            }
            return View();
        }

        public ActionResult Careers()
        {
            if (Request.IsAjaxRequest())
            {
                return PartialView();
            }
            return View();
        }
    }
}

Week6CodeChallenge/Views/About/How.cshtml
@{
    ViewBag.Title = "How";
    if (!Request.IsAjaxRequest())
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
}

<h2>How</h2>

Week6CodeChallenge/Views/About/Index.cshtml
@{
    ViewBag.Title = "Index";
    if (!Request.IsAjaxRequest())
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
}

<div class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <div class="tabbable" id="tabs-299305">
                <ul class="nav nav-tabs">
                    <li class="active">
                        <a data-url="@Url.Action("Who", "About")" class="ajax-tab">Who</a>
                    </li>
                    <li>
                        <a data-url="@Url.Action("What", "About")" class="ajax-tab">What</a>
                    </li>
                    <li>
                        <a data-url="@Url.Action("Why", "About")" class="ajax-tab">Why</a>
                    </li>
                    <li>
                        <a data-url="@Url.Action("How", "About")" class="ajax-tab">How</a>
                    </li>
                    <li>
                        <a data-url="@Url.Action("Where", "About")" class="ajax-tab">Where</a>
                    </li>
                </ul>
                <div class="tab-content">
                @Html.Partial("Who")
                </div>
            </div>
        </div>
    </div>
</div>

Week6CodeChallenge/Views/About/What.cshtml
@{
    ViewBag.Title = "What";
    if (!Request.IsAjaxRequest())
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }}

<h2>What</h2>

Week6CodeChallenge/Views/About/Where.cshtml
@{
    ViewBag.Title = "Where";
    if (!Request.IsAjaxRequest())
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }}

<h2>Where</h2>

Week6CodeChallenge/Views/About/Who.cshtml
@{
    ViewBag.Title = "Who";
    if (!Request.IsAjaxRequest())
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }}

<h2>Who</h2>

Week6CodeChallenge/Views/About/Why.cshtml
@{
    ViewBag.Title = "Why";
    if (!Request.IsAjaxRequest())
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }}

<h2>Why</h2>

Week6CodeChallenge/Views/Contact/Index.cshtml
@model Week6CodeChallenge.Models.ContactForm

@{
    Layout = null;
}
<div class="ajax-form-content">
        <form data-posturl="@Url.Action("Index", "Contact")" method="post" class="ajax-form">
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>ContactForm</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.ProjectDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ProjectDescription, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ProjectDescription, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    </form>
</div>

Week6CodeChallenge/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    if (!Request.IsAjaxRequest())
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
  }

<div class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <img alt="140x140" src="http://tinyurl.com/if-suhbg" />
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-md-4 column">
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum
        </div>
        <div class="col-md-4 column">
            It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
        </div>
        <div class="col-md-4 column">
            There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.
        </div>
    </div>
</div>

Week6CodeChallenge/Views/Home/Work.cshtml
@{
    ViewBag.Title = "Work";
    if (!Request.IsAjaxRequest())
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
  }

<div class="container">
    <div class="row clearfix">
        <div class="col-md-6 column">
            <img style="width: 400px; height: 400px;" src="http://tinyurl.com/qeemlqf" />
            <p> Work Sample 1</p>
        </div>
        <div class="col-md-6 column">
            <img style="width: 400px; height: 400px;" src="http://tinyurl.com/qeemlqf" />
            <p> Work Sample 2</p>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-md-6 column">
            <img style="width: 400px; height: 400px;" src="http://tinyurl.com/qeemlqf" />
            <p> Work Sample 3</p>
        </div>
        <div class="col-md-6 column">
            <img style="width: 400px; height: 400px;" src="http://tinyurl.com/qeemlqf" />
            <p> Work Sample 4</p>
        </div>
    </div>
</div>

Week6CodeChallenge/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="~/Scripts/jquery-1.11.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/Main.js"></script>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Josh Harbaugh Portfolio</title>
    <!-- Bootstrap Core CSS - Uses Bootswatch Flatly Theme: http://bootswatch.com/flatly/ -->
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet">

    
</head>
<body id="page-top" class="index">
    
        <div class="container">
            <nav class="navbar">
                <div class="row">
            <img class="navbar-left" src="http://cdn-img.easylogo.cn/gif/51/51700.gif" />
                <div class="navbar-right" style="line-height: 170px;">
                    <ul class="list-inline">
                    <li data-url="@Url.Action("Index", "Home")" class="ajax-link"> Home</li>
                    <li data-url="@Url.Action("Index", "About")" class="ajax-link">About</li>
                    <li data-url="@Url.Action("Work", "Home")" class="ajax-link">Work</li>
                    <li data-url="@Url.Action("Careers", "Home")" class="ajax-link">Careers</li>
                    <li data-url="@Url.Action("Index", "Contact")" class="ajax-link">Contact</li>
                    </ul>
                </div>
            </div>
            </nav>
            </div>

    <div id="content">
    @RenderBody()
    </div>
</body>
</html>